## Max pooling

In [ ]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

max_pooling = keras.layers.MaxPooling2D(pool_size=2)

data = np.array([[1, 5, 3, 7],
                 [7, 3, 9, 2],
                 [3, 5, 8, 4],
                 [8, 7, 3, 5]])
data = data.reshape(1, 4, 4, 1)

data = tf.Variable(data)
print(' data: \n', data[0,:,:,0])

after_mp = max_pooling(data)
print('\n\n after_mp: \n', after_mp[0,:,:,0])

In [ ]:
# max_pooling

import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

max_pooling = keras.layers.MaxPooling2D(pool_size=2, strides=2)

data_X = np.array([[1, 5, 3, 7],
                   [7, 3, 9, 2],
                   [3, 5, 8, 4],
                   [8, 7, 3, 5]])
data_X = data_X.reshape(1, 4, 4, 1)
data_X = tf.Variable(data_X, dtype=tf.float32)

data_y = np.ones((1, 2, 2, 1))
data_y = tf.Variable(data_y, dtype=tf.float32)

print('\n\n data_X: \n', data_X[0,:,:,0])
print('\n\n data_y: \n', data_y[0,:,:,0])

with tf.GradientTape(persistent=True) as tape:
    data_after = max_pooling(data_X)
    print('\n\n data_after: \n', data_after[0,:,:,0])
    
    loss = tf.reduce_mean((data_after-data_y)**2)
    print('\n\n loss: \n', loss)
    
dloss = tape.gradient(loss, data_after)
print('\n\n dloss: \n', dloss[0,:,:,0])

ddata_X = tape.gradient(loss, data_X)
print('\n\n ddata_X: \n', ddata_X[0,:,:,0])

## Average pooling

In [ ]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

avg_pooling = keras.layers.AveragePooling2D(pool_size=2)

data = np.array([[1, 5, 3, 7],
                 [7, 3, 9, 2],
                 [3, 5, 8, 4],
                 [8, 7, 3, 5]])
data = data.reshape(1, 4, 4, 1)

data = tf.Variable(data, dtype=tf.float32)
print(' data: \n', data[0,:,:,0])

after_mp = max_pooling(data)
print('\n\n after_mp: \n', after_mp[0,:,:,0])

In [1]:
# AveragePooling2D

import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

avg_pooling = keras.layers.AveragePooling2D(pool_size=2, strides=2)

data_X = np.array([[1, 5, 3, 7],
                   [7, 3, 9, 2],
                   [3, 5, 8, 4],
                   [8, 7, 3, 5]])
data_X = data_X.reshape(1, 4, 4, 1)
data_X = tf.Variable(data_X, dtype=tf.float32)

data_y = np.ones((1, 2, 2, 1))
data_y = tf.Variable(data_y, dtype=tf.float32)

print('\n\n data_X: \n', data_X[0,:,:,0])
print('\n\n data_y: \n', data_y[0,:,:,0])

with tf.GradientTape(persistent=True) as tape:
    data_after = avg_pooling(data_X)
    print('\n\n data_after_ap: \n', data_after[0,:,:,0])
    
    loss = tf.reduce_mean((data_after-data_y)**2)
    print('\n\n loss: \n', loss)
    
dloss = tape.gradient(loss, data_after)
print('\n\n dloss: \n', dloss[0,:,:,0])

ddata_X = tape.gradient(loss, data_X)
print('\n\n ddata_X: \n', ddata_X[0,:,:,0])



 data_X: 
 tf.Tensor(
[[1. 5. 3. 7.]
 [7. 3. 9. 2.]
 [3. 5. 8. 4.]
 [8. 7. 3. 5.]], shape=(4, 4), dtype=float32)


 data_y: 
 tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


 data_after_ap: 
 tf.Tensor(
[[4.   5.25]
 [5.75 5.  ]], shape=(2, 2), dtype=float32)


 loss: 
 tf.Tensor(16.40625, shape=(), dtype=float32)


 dloss: 
 tf.Tensor(
[[1.5   2.125]
 [2.375 2.   ]], shape=(2, 2), dtype=float32)


 ddata_X: 
 tf.Tensor(
[[0.375   0.375   0.53125 0.53125]
 [0.375   0.375   0.53125 0.53125]
 [0.59375 0.59375 0.5     0.5    ]
 [0.59375 0.59375 0.5     0.5    ]], shape=(4, 4), dtype=float32)


## Convolution

In [2]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

conv2D = keras.layers.Conv2D(1, (2, 2), activation='relu')

data_X = np.array([[1, 1, 2],
                   [1, 2, 1],
                   [2, 1, 1]])
data_X = data_X.reshape(1, 3, 3, 1)
data_X = tf.Variable(data_X, dtype=tf.float32)

data_y = np.ones((1, 2, 2, 1))
data_y = tf.Variable(data_y, dtype=tf.float32)

print('\n\n data_X: \n', data_X[0,:,:,0])
print('\n\n data_y: \n', data_y[0,:,:,0])

with tf.GradientTape(persistent=True) as tape: 
    data_after_conv = conv2D(data_X)
    print('\n\n data_after_conv: \n', data_after_conv[0,:,:,0])
    
    # Check the values of the current conv weight
    print('\n\n conv_weight: \n', conv2D.trainable_weights[0][:,:,0,0])
    print('\n conv_bias: \n', conv2D.trainable_weights[1][0])
        
    loss = tf.reduce_mean((data_after_conv-data_y)**2)
    print('\n\n loss: \n', loss)
    
dloss = tape.gradient(loss, data_after_conv)
print('\n\n dloss: \n', dloss[0,:,:,0])

dconv_weight = tape.gradient(loss, conv2D.trainable_weights)
print('\n\n dconv_weight: \n', dconv_weight[0][:,:,0,0])
print('\n dconv_bias: \n', dconv_weight[1][0])



 data_X: 
 tf.Tensor(
[[1. 1. 2.]
 [1. 2. 1.]
 [2. 1. 1.]], shape=(3, 3), dtype=float32)


 data_y: 
 tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


 data_after_conv: 
 tf.Tensor(
[[1.1864988  0.7961735 ]
 [0.7961735  0.23312974]], shape=(2, 2), dtype=float32)


 conv_weight: 
 tf.Tensor(
[[-0.32082075  0.7238367 ]
 [-0.48161376  0.6325483 ]], shape=(2, 2), dtype=float32)

 conv_bias: 
 tf.Tensor(0.0, shape=(), dtype=float32)


 loss: 
 tf.Tensor(0.17649058, shape=(), dtype=float32)


 dloss: 
 tf.Tensor(
[[ 0.09324938 -0.10191324]
 [-0.10191324 -0.38343513]], shape=(2, 2), dtype=float32)


 dconv_weight: 
 tf.Tensor(
[[-0.87744737 -0.6978387 ]
 [-0.6978387  -0.40076286]], shape=(2, 2), dtype=float32)

 dconv_bias: 
 tf.Tensor(-0.49401224, shape=(), dtype=float32)


## Activation function

In [ ]:
# sigmoid

import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

sigmoid_activation = keras.activations.sigmoid

data_X = np.array([[-3, 9, 2],
                   [5, -8, 4],
                   [-7, 3, 5]])
data_X = data_X.reshape(1, 3, 3, 1)
data_X = tf.Variable(data_X, dtype=tf.float32)

data_y = np.ones((1, 3, 3, 1))
data_y = tf.Variable(data_y, dtype=tf.float32)

print('\n\n data_X: \n', data_X[0,:,:,0])
print('\n\n data_y: \n', data_y[0,:,:,0])

with tf.GradientTape(persistent=True) as tape:
    data_after = sigmoid_activation(data_X)
    print('\n\n data_after: \n', data_after[0,:,:,0])
    
    loss = tf.reduce_mean((data_after-data_y)**2)
    print('\n\n loss: \n', loss)
    
dloss = tape.gradient(loss, data_after)
print('\n\n dloss: \n', dloss[0,:,:,0])

ddata_X = tape.gradient(loss, data_X)
print('\n\n ddata_X: \n', ddata_X[0,:,:,0])

In [ ]:
# tanh

import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

tanh_activation = keras.activations.tanh

data_X = np.array([[-1, 0.6, 0.3],
                   [5, -8, 4],
                   [-7, 3, 5]])
data_X = data_X.reshape(1, 3, 3, 1)
data_X = tf.Variable(data_X, dtype=tf.float32)

data_y = np.ones((1, 3, 3, 1))
data_y = tf.Variable(data_y, dtype=tf.float32)

print('\n\n data_X: \n', data_X[0,:,:,0])
print('\n\n data_y: \n', data_y[0,:,:,0])

with tf.GradientTape(persistent=True) as tape:
    data_after = tanh_activation(data_X)
    print('\n\n data_after: \n', data_after[0,:,:,0])
    
    loss = tf.reduce_mean((data_after-data_y)**2)
    print('\n\n loss: \n', loss)
    
dloss = tape.gradient(loss, data_after)
print('\n\n dloss: \n', dloss[0,:,:,0])

ddata_X = tape.gradient(loss, data_X)
print('\n\n ddata_X: \n', ddata_X[0,:,:,0])

In [ ]:
# relu

import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

relu_activation = keras.activations.relu

data_X = np.array([[1, 5, 3, -7],
                   [7, -3, 9, 2],
                   [3, 5, -8, 4],
                   [8, -7, 3, 5]])
data_X = data_X.reshape(1, 4, 4, 1)
data_X = tf.Variable(data_X, dtype=tf.float32)

data_y = np.ones((1, 4, 4, 1))
data_y = tf.Variable(data_y, dtype=tf.float32)

print('\n\n data_X: \n', data_X[0,:,:,0])
print('\n\n data_y: \n', data_y[0,:,:,0])

with tf.GradientTape(persistent=True) as tape:
    data_after = relu_activation(data_X)
    print('\n\n data_after: \n', data_after[0,:,:,0])
    
    loss = tf.reduce_mean((data_after-data_y)**2)
    print('\n\n loss: \n', loss)
    
dloss = tape.gradient(loss, data_after)
print('\n\n dloss: \n', dloss[0,:,:,0])

ddata_X = tape.gradient(loss, data_X)
print('\n\n ddata_X: \n', ddata_X[0,:,:,0])

In [ ]:
# PReLU

import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

prelu_activation = keras.layers.Activation(tf.keras.layers.PReLU())

data_X = np.array([[1, 5, 3, -7],
                   [7, -3, 9, 2],
                   [3, 5, -8, 4],
                   [8, -7, 3, 5]])
data_X = data_X.reshape(1, 4, 4, 1)
data_X = tf.Variable(data_X, dtype=tf.float32)

data_y = np.ones((1, 4, 4, 1))
data_y = tf.Variable(data_y, dtype=tf.float32)

print('\n\n data_X: \n', data_X[0,:,:,0])
print('\n\n data_y: \n', data_y[0,:,:,0])

with tf.GradientTape(persistent=True) as tape:
    data_after = prelu_activation(data_X)
    print('\n\n data_after_mp: \n', data_after[0,:,:,0])
    
    loss = tf.reduce_mean((data_after-data_y)**2)
    print('\n\n loss: \n', loss)
    
dloss = tape.gradient(loss, data_after)
print('\n\n dloss: \n', dloss[0,:,:,0])

ddata_X = tape.gradient(loss, data_X)
print('\n\n ddata_X: \n', ddata_X[0,:,:,0])

In [ ]:
# softplus

import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

softplus_activation = tf.keras.activations.softplus

data_X = np.array([[1, 5, 3, -7],
                   [7, -3, 9, 2],
                   [3, 5, -8, 4],
                   [8, -7, 3, 5]])
data_X = data_X.reshape(1, 4, 4, 1)
data_X = tf.Variable(data_X, dtype=tf.float32)

data_y = np.ones((1, 4, 4, 1))
data_y = tf.Variable(data_y, dtype=tf.float32)

print('\n\n data_X: \n', data_X[0,:,:,0])
print('\n\n data_y: \n', data_y[0,:,:,0])

with tf.GradientTape(persistent=True) as tape:
    data_after = softplus_activation(data_X)
    print('\n\n data_after_mp: \n', data_after[0,:,:,0])
    
    loss = tf.reduce_mean((data_after-data_y)**2)
    print('\n\n loss: \n', loss)
    
dloss = tape.gradient(loss, data_after)
print('\n\n dloss: \n', dloss[0,:,:,0])

ddata_X = tape.gradient(loss, data_X)
print('\n\n ddata_X: \n', ddata_X[0,:,:,0])